<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="Azure.AI.OpenAI" Version="2.9.0-beta.1" />
      <PackageReference Include="DevExpress.AIIntegration.Blazor.Chat.WebView" Version="26.1.*-*" />
      <PackageReference Include="DevExpress.AIIntegration.Wpf.Chat" Version="26.1.*-*" />
      <PackageReference Include="DevExpress.Wpf.ThemesLW" Version="26.1.*-*" />
      <PackageReference Include="Markdig" Version="0.41.1" />
      <PackageReference Include="Microsoft.Extensions.AI" Version="10.6.0" />
      <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.6.0" />
  </ItemGroup>

</Project>
